### ISSUE TITLE
Time complexity of search function

### ISSUE THREAD

**Issue by beanpuppy** [jn8029/VocabularyHighlighter#3]
I read on your website that you tried to make the search on words to be efficient and got it to  O(n*log(m)) using a hash of arrays. 

But I think the much simpler solution of using a [set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) instead would be faster.

It would look something like this:

```javascript
// Where wordlist is something like:
// let wordlist = new Set(['word', 'otherword', ...]);
function find_key_words_in_node(node, wordlist) {
   return node.nodeValue.split(' ').map(word => {
       if (wordlist.has(word)) return word;
    });
}
```

This would be O(m) because `Set.prototype.has(value)` has O(1) time complexity.

**Comment by jn8029** [comment]
@beanpuppy 

you are right that using a set is faster. 

My article is actually incorrect in saying :

```
let wordlist = {
  'a':['abandon',...],
  'b':['bag',...],
  ...
}
```

<strong>With this wordlist object, the search can be performed more efficiently by taking the leading alphabet of the word to retrieve the array from the object, and then use the binary search algorithm to find the word. This implementation can check the existence of a word in the word list at O(n*log(m))</strong>


The fact is given the structure the wordlist would always have 26 alphabets as keys (a-z). getting the right array with words that start with a certain alphabet takes constant time. So finding the word itself takes O(26 + ln(n)) = O(ln(n)) and n is the number of words in the array.

With a set or a hash table, the structure can be edited to be 

```
let wordlist = {
  'a':set('abandon'.....),
  'b':set('bag'....),
  ...
}
```

With this new structure the time complexity of finding the word is then O(26 + 1) = O(1).

Thanks for your input!
